### ISSUE TITLE
Research changes needed to our monitoring setup

### ISSUE THREAD

**Issue by lfrancke** [stackabletech/issues#132]
We will move away from the Agent and towards a Kubernetes-native solution with the Kubelet.
As such it is unclear whether we want to keep using our own Monitoring operator or whether we want to use an existing K8s operators for this.

This ticket serves as a research ticket.

**Comment by fhennig** [comment]
##### Existing Monitoring Tooling

There is an existing [prometheus-operator](https://github.com/prometheus-operator/prometheus-operator) and there is also [kube-prometheus](https://github.com/prometheus-operator/kube-prometheus), a collection of manifests to run prometheus, grafana, alertmanager and all the rest of the stack. It supports a node_exporter and it is possible to setup custom scrape jobs which we could use to define out own pod scraping ([PodMonitor](https://prometheus-operator.dev/docs/operator/design/#podmonitor)).

Documentation is a bit incomplete and fragmented in certain places, which makes setting it up a bit complicated.

From a user perspective, it has a very configuration setup than all our other operators, which might be an issue.

##### Our own Operator

It needs to be updated to the k8s infrastructure and some changes to the node-exporter might be required, but other than that, if it works, I'd say we could just keep using it.

I realize this is not the most thorough answer. I tried to quickly get the official prometheus-operator to run with a custom scrape job but couldn't wrap my head aroud it quickly enough. I'd suggest as a next step to either stick with our operator for now if there's nothing it's missing, and/or develop a Spike with the official prometheus-operator to evaluate whether it could be a good replacement or not.

**Comment by fhennig** [comment]
##### Getting Spark Pods to be Scraped

I did a Spike to get our pods to be scraped with the prometheus-operator. I didn't use the full node-prometheus setup. Steps to get it to work:
- Setup a kind cluster
- Deploy a simple Spark cluster using the Stackable operator.
- Deploy the prometheus-operator by running `kubectl create -f bundle.yaml` with the bundle from the [repository](https://github.com/prometheus-operator/prometheus-operator).
- A `ServiceAccount` with special permissions is needed. To configure that, follow the [steps in the getting started guide](https://github.com/prometheus-operator/prometheus-operator/blob/main/Documentation/user-guides/getting-started.md#enable-rbac-rules-for-prometheus-pods) to create a `ClusterRole`, `ServiceAccount` and `ClusterRoleBinding`.
- Now a prometheus instance can be deployed with the created `prometheus` `ServiceAccount`:
```
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: prometheus
spec:
  serviceAccountName: prometheus
  podMonitorSelector:
    matchLabels:
      team: stackable
  resources:
    requests:
      memory: 400Mi
  enableAdminAPI: false
```
This should lead to the creation of a `prometheus-prometheus0` pod. The configured `podMonitorSelector` selects all `PodMonitor`s that are tagged with `team=stackable`. We will create a `PodMonitor` to scrape our Spark pods next:
```
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: stackable
  labels:
    team: stackable
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: spark
  podMetricsEndpoints:
  - port: metrics
```
The `PodMonitor` has the label referenced above. It uses `matchLabels` to select the Pods by label. We also configure which port we want to scrape the metrics from.

That's it! You should now be able to access prometheus with `kubectl port-forward svc/prometheus-operated 9090` and see the metrics as well as the two targets (master and slave Spark pod).
