### ISSUE TITLE
Architecture Design: LDAP References

### ISSUE THREAD

**Issue by lfrancke** [stackabletech/issues#170]
This ticket covers coming up with a design to specify LDAP details for our products.
If we were to use the "normal" configuration objects it'd mean users might have to create the same data multiple times as many of our products take very similar options. It also would contain things like passwords which should be secured and as such might need to be refactored into secrets anyway.

One idea floated by @soenkeliebau was to have a Stackable `LdapReference` (name tbd.) object that encapsulates everything needed. The question is still how Secrets would be handled here.
An idea by @Jimvin was to have a more generic `StackableAuthentication` object (name made up by me) which would have a `type` and depending on the type would take different fields (e.g. `ldap`, `kerberos` etc.).
Another idea is just to use a Secret or ConfigMap with a well-known structure.

Please come up with a proposal that ideally suites every product we currently have and which allows for reusing of information across these products while keeping credentials secure.

As far as I'm concerned I'm fine with limiting the scope to LDAP for now but it obviously doesn't hurt to keep other methods in mind.

The result should be presented in the weekly architecture meeting as well as documented in an ADR

**Comment by teozkr** [comment]
First draft designed together with @Jimvin:

```yaml
---
# authn_obj
apiVersion: authentication.stackable.tech/v1alpha1
kind: AuthenticationClass
metadata:
    name: common-ldap
spec:
    ldap:
        hostname: ldap.server
        port: 389
        domain: domain.local
        domainInUsername: true
        tls:
            secretClass: tls
        bindCredentials:
            secretClass: common-ldap-bind
            scope: Service

---
# tls secretclass
apiVersion: secrets.stackable.tech/v1alpha1
kind: SecretClass
metadata:
    name: tls
spec:
    backend:
        autoTls:
            ca:
                secret: tls-ca

---
# ldap bind secretclass
apiVersion: secrets.stackable.tech/v1alpha1
kind: SecretClass
metadata:
    name: common-ldap-bind
spec:
    backend:
        k8sSearch:
            searchLabels:
                # defined by user
                ldap-bind: common-ldap

---
# ldap bind secret
apiVersion: v1
kind: Secret
metadata:
    name: nifi-ldap-bind
    labels:
        ldap-bind: common-ldap
        secrets.stackable.tech/service: nifi

---
# nifi cluster
apiVersion: nifi.stackable.tech/v1alpha1
kind: NifiCluster
metadata:
    name: nifi
spec:
    authenticationConfig:
        methods:
          - authenticationClass: common-ldap
          - singleUser:
              secretName: nifi-admin-credentials-simple
              generateCredentials: true
    # ... rolegroup stuff
```

Currently we're leaning towards putting this CRD into a new commons "operator".
