### ISSUE TITLE
AuthenticationClass for LDAP

### ISSUE THREAD

**Issue by teozkr** [stackabletech/issues#173]
This will probably have to live in a new "commons operator" of some sort, since we don't want this to be owned by a single product.

**Comment by teozkr** [comment]
First draft designed together with @Jimvin:

```yaml
---
# authn_obj
apiVersion: authentication.stackable.tech/v1alpha1
kind: AuthenticationClass
metadata:
    name: common-ldap
spec:
    ldap:
        hostname: ldap.server
        port: 389
        domain: domain.local
        domainInUsername: true
        tls:
            secretClass: tls
        bindCredentials:
            secretClass: common-ldap-bind
            scope: Service

---
# tls secretclass
apiVersion: secrets.stackable.tech/v1alpha1
kind: SecretClass
metadata:
    name: tls
spec:
    backend:
        autoTls:
            ca:
                secret: tls-ca

---
# ldap bind secretclass
apiVersion: secrets.stackable.tech/v1alpha1
kind: SecretClass
metadata:
    name: common-ldap-bind
spec:
    backend:
        k8sSearch:
            searchLabels:
                # defined by user
                ldap-bind: common-ldap

---
# ldap bind secret
apiVersion: v1
kind: Secret
metadata:
    name: nifi-ldap-bind
    labels:
        ldap-bind: common-ldap
        secrets.stackable.tech/service: nifi

---
# nifi cluster
apiVersion: nifi.stackable.tech/v1alpha1
kind: NifiCluster
metadata:
    name: nifi
spec:
    authenticationConfig:
        methods:
          - authenticationClass: common-ldap
          - singleUser:
              secretName: nifi-admin-credentials-simple
              generateCredentials: true
    # ... rolegroup stuff
```
