### ISSUE TITLE
Open-shift: eliminate warnings on operator start-up

### ISSUE THREAD

**Issue by adwk67** [stackabletech/issues#340]
#### The issue

Starting up an operator in open-shift version 4.11 results in warnings such as these:

```
[INFO ] Installing airflow operator in version 23.1.0
W0126 16:19:17.664791  439339 warnings.go:70] would violate PodSecurity "restricted:v1.24": 
allowPrivilegeEscalation != false (container "airflow-operator" must set securityContext.allowPrivilegeEscalation=false), 
unrestricted capabilities (container "airflow-operator" must set securityContext.capabilities.drop=["ALL"]), 
runAsNonRoot != true (pod or container "airflow-operator" must set securityContext.runAsNonRoot=true), 
seccompProfile (pod or container "airflow-operator" must set securityContext.seccompProfile.type to "RuntimeDefault" or "Localhost")
```
These warnings may evolve into errors in [future](https://cloud.redhat.com/blog/pod-security-admission-in-openshift-4.11) releases:

> In a subsequent release, we intend to move the global configuration to enforce the “restricted” pod security profile globally. With this change, the label synchronization mechanism will also switch into a mode where it synchronizes the “enforce” Pod Security Admission label rather than the “audit” and “warn”. To ensure an upgrade is safe, we are also introducing an information-level alert on pod security violations in 4.11.

It is therefore necessary to deal with these warnings sooner or later. These warnings do not appear in version 4.9 (unclear as to the status with 4.10).

The current status is:

| Version | *scc | Operator namespace | Warnings on deploy | Job runs |
| :--- | :--- | :--- | :--- | :--- |
| 4.9 | no | default | none | yes |
| 4.9 | no | non-default | none | yes |
| 4.9 | yes | default | none | yes |
| 4.9 | yes | non-default | none | yes |
| 4.11 | default | yes (will result in errors > 4.11) | yes |

*scc: SCC definition in `values.yaml` i.e.

```
securityContext:
  capabilities:
    drop:
      - ALL
  readOnlyRootFilesystem: false
  allowPrivilegeEscalation: false
  runAsNonRoot: true
  runAsUser: 1000680010
```
This definition does not set `seccompProfile` to `type: RuntimeDefault`, which may be required to avoid warnings/errors in versions 4.11+. See [these](https://bugzilla.redhat.com/show_bug.cgi?id=2010564) [links](https://docs.openshift.com/container-platform/4.11/security/seccomp-profiles.html) for changes that may be necessary.

________________________________________
#### The solution

Extend securityContext in the helm values.yaml to address the issues in the warning. For airflow, it looks like this:

```
securityContext:
  capabilities:
    drop:
    - ALL
  allowPrivilegeEscalation: false
  seccompProfile:
    type: RuntimeDefault
  # readOnlyRootFilesystem: true
  # openshift requires a UID if one is not given in the image definition (e.g. "stackable")
  # to verify that the user is non-root
  runAsNonRoot: true
  runAsUser: 1000
```

This only "works" when operators are deployed to the default namespace, so it is not a viable way forward. We will need version-specific manifests that can be invoked depending on the environment etc.

#### Acceptance criteria
Warnings eliminated for all relevant operators:

```[tasklist]
- [ ] airflow
- [ ] commons
- [ ] druid
- [ ] hive
- [ ] hbase
- [ ] hdfs
- [ ] kafka
- [ ] listener
- [ ] nifi
- [ ] opa
- [x] secret (requires higher privileges and will be looked at separately in the context of certification)
- [ ] spark-k8s
- [ ] superset
- [ ] trino
- [ ] zookeeper
```
