### ISSUE TITLE
Support mounting arbitrary SecretClasses in all operators

### ISSUE THREAD

**Issue by sbernauer** [stackabletech/issues#356]
Sometimes our uses need the flexibility to mount arbitrary SecretClasses. Some uses-cases could be:

* Ingest data from tls-enabled Kafka into Druid.
* Use NiFi to access tls-enabled Stackable services such as Trino
* Access tls-enabled Trino from Superset (we currently don't have a TrinoConnection object)

Some use-cases can't be entered into the CRDs, so the users needs the flexibility to mount *any* SecretClass *anywhere*.
All of the stuff can be done via a `podOverwrite` (see https://github.com/stackabletech/issues/issues/346), but I claim it will be used often enough and is complicated enough to justify a dedicated field.
A CRD suggestion could look like
```
spec:
  [...]
    certificateMounts:
      - secretClass: my-secret-class # mandatory
        secretClassScopes: node,pod,service=secret-consumer-nginx # optional, defaults to node,pod
        mountPath: /stackable/certificates/<secretClass> # optional, if not specified defaults to /stackable/certificates/<secretClass>
```
