### ISSUE TITLE
Distinguish between image name and repository in our Helm

### ISSUE THREAD

**Issue by soenkeliebau** [stackabletech/issues#363]
In our Helm charts we [set](https://github.com/stackabletech/commons-operator/blob/632af2d7c2104c11ff2497ccb738fba5073b065a/deploy/helm/commons-operator/values.yaml#L3) the image name and registry together at the moment:

```yaml
# Default values for commons-operator.
---
image:
  repository: docker.stackable.tech/stackable/commons-operator
  pullPolicy: IfNotPresent
```

Quite often people will only want to override the registry to use, in offline deployments for example.

It might make sense to split image name and registry url into two variables to allow for more ease of use here.
