### ISSUE TITLE
Fix GitHub Actions deprecations

### ISSUE THREAD

**Issue by lfrancke** [stackabletech/issues#365]
There are two deprecations that will make a bunch of our builds break in the near future.
We need to fix those across our repositories:

- https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/ - this is already fixed in operator-templating but not in other repositories (e.g. operator-rs) - 31.5.2023 is the deadline
- https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/ - this is _partially_ fixed in operator-templating but not in others, GitHub has not announced a final date when Node 12 actions will start to fail, we should still get this fixed

The second bit means that we cannot use the actions-rs actions anymore as they are not updated anymore.

**Comment by Techassi** [comment]
# Action Deprecations

First round of research about the above mentioned action deprecations. I checked most of the stuff, but there might be some small stuff left.

## save-state and set-output

> https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

- The npm dependency `@actions/core` needs to updated to `v1.10.0` or greater.
- Workflows using `save-state` and/or `set-output` via stdout need to update to use the new ENV variables.

## Node 12 to Node 16 update

> https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/

- All actions need to run on Node 16
- All used actions need to be updated to a version with runs on Node 16

---

## operator-rs

> `build.yaml`

| Action                          | Current version | Latest version | Notes                                                                                                                                                                             |
| ------------------------------- | --------------- | -------------- | --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- |
| actions/checkout                | 3.3.0           | 3.5.2          | Version `3.3.0` already uses `@actions/core` version `^v1.10.0`                                                                                                                   |
| actions-rs/toolchain            | 1.0.7           | 1.0.6          | Version `1.0.7` doesn't seem to exist or the tag was deleted. The action uses `@actions/core` version `^1.2.0`. Needs to be updated. See [below](#required-changes) for solution. |
| Swatinem/rust-cache             | 2.2.0           | 2.4.0          | Version `2.2.0` already uses `@actions/core` version `^1.10.0`                                                                                                                    |
| actions-rs/cargo                | 1.0.3           | 1.0.1          | Version `1.0.3` doesn't seem to exist or the tag was deleted. The action uses `@actions/core` version `^1.2.4`. Needs to be updated. See [below](#required-changes) for solution. |
| EmbarkStudios/cargo-deny-action | 1.4.0           | 1.5.2          | Needs no update, doesn't use `@actions/core` or the deprecated commands.                                                                                                          |
| actions-rs/clippy-check         | 1.0.7           | 1.0.7          | The action uses `@actions/core` version `^1.2.4`. Needs to be updated. See [below](#required-changes) for solution.                                                               |

> `daily_security.yml` <<< This is triggering me

| Action                 | Current version | Latest version | Notes                                                                                                               |
| ---------------------- | --------------- | -------------- | ------------------------------------------------------------------------------------------------------------------- |
| actions-rs/audit-check | 1.2.0           | 1.2.0          | The action uses `@actions/core` version `^1.2.4`. Needs to be updated. See [below](#required-changes) for solution. |

> `reviewdog.yaml`

| Action                          | Current version | Latest version | Notes                                                                    |
| ------------------------------- | --------------- | -------------- | ------------------------------------------------------------------------ |
| reviewdog/action-actionlint     | 1.36.0          | 1.37.0         | Needs no update, doesn't use `@actions/core` or the deprecated commands. |
| reviewdog/action-detect-secrets | 0.11.3          | 0.11.5         | Needs no update, doesn't use `@actions/core` or the deprecated commands. |
| reviewdog/action-markdownlint   | 0.9             | 0.10.0         | Needs no update, doesn't use `@actions/core` or the deprecated commands. |
| reviewdog/action-yamllint       | 1.6.1           | 1.6.1          | Needs no update, doesn't use `@actions/core` or the deprecated commands. |

## operator-templating

> `reviewdog.yaml`

| Action                      | Current version | Latest version | Notes                                                                                                                         |
| --------------------------- | --------------- | -------------- | ----------------------------------------------------------------------------------------------------------------------------- |
| actions/setup-python        | 4               | 4.6.0          | Version `4.0.0` uses uses `@actions/core` version `^1.2.3`. Needs to be updated. See [below](#required-changes) for solution. |
| reviewdog/action-flake8     | 3.6.0           | 3.6.3          | Needs no update, doesn't use `@actions/core` or the deprecated commands.                                                      |
| reviewdog/action-hadolint   | 1.34.1          | 1.34.1         | Needs no update, doesn't use `@actions/core` or the deprecated commands.                                                      |
| reviewdog/action-shellcheck | 1.17.0          | 1.17.0         | Needs no update, doesn't use `@actions/core` or the deprecated commands.                                                      |

> `run.yml` <<< Again?

Nothing.

---

## Required changes

### `action-rs` related changes

All `action-rs` actions need to be swapped out as they are no longer maintained, use an oudated `@actions/core` version
and won't run on Node 16. It can be replaced with [dtolnay/rust-toolchain][1].

<details>
<summary>An adjusted worflow could look like this</summary>

**NOTE:** This is untested. The workflow might need additional tweaking.

```yaml
---
name: Stackable Build Pipeline

on:
  push:
    branches:
      - main
      - staging
      - trying
      - "renovate/**"
    tags:
      - "*"
  pull_request:

env:
  CARGO_TERM_COLOR: always
  CARGO_INCREMENTAL: '0'
  CARGO_PROFILE_DEV_DEBUG: '0'
  RUST_TOOLCHAIN_VERSION: "1.65.0"
  RUSTFLAGS: "-D warnings"
  RUSTDOCFLAGS: "-D warnings"
  RUST_LOG: "info"

jobs:
  # Identify unused dependencies
  run_udeps:
    name: Run Cargo Udeps
    runs-on: ubuntu-latest
    env:
      RUSTC_BOOTSTRAP: 1
    steps:
      - uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3.3.0
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: ${{ env.RUST_TOOLCHAIN_VERSION }}
      - uses: Swatinem/rust-cache@359a70e43a0bb8a13953b04a90f76428b4959bb6 # v2.2.0
        with:
          key: udeps
      - run: cargo install cargo-udeps --locked
      - run: udeps --all-targets

  run_cargodeny:
    name: Run Cargo Deny
    runs-on: ubuntu-latest
    strategy:
      matrix:
        checks:
          - advisories
          - bans licenses sources

    # Prevent sudden announcement of a new advisory from failing ci:
    continue-on-error: ${{ matrix.checks == 'advisories' }}

    steps:
      - uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3.3.0
      - uses: EmbarkStudios/cargo-deny-action@8a8607bd8e2b3a514d5a40174cc7c55b229d9ba7 # v1.4.0
        with:
          command: check ${{ matrix.checks }}

  run_rustfmt:
    name: Run Rustfmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3.3.0
      - uses: actions-rs/toolchain@16499b5e05bf2e26879000db0c1d13f7e13fa3af # renovate: tag=v1.0.7
        with:
          profile: minimal
          toolchain: ${{ env.RUST_TOOLCHAIN_VERSION }}
          components: rustfmt
          override: true
      - uses: actions-rs/cargo@844f36862e911db73fe0815f00a4a2602c279505 # renovate: tag=v1.0.3
        with:
          command: fmt
          args: --all -- --check

  run_clippy:
    name: Run Clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3.3.0
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: ${{ env.RUST_TOOLCHAIN_VERSION }}
          components: clippy
      - uses: Swatinem/rust-cache@359a70e43a0bb8a13953b04a90f76428b4959bb6 # v2.2.0
        with:
          key: clippy
      - name: Run clippy manually without annotations
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        if: env.GITHUB_TOKEN == null
        run: cargo clippy --all-targets -- -D warnings

  run_rustdoc:
    name: Run RustDoc
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3.3.0
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: ${{ env.RUST_TOOLCHAIN_VERSION }}
          components: rustfmt
      - uses: Swatinem/rust-cache@359a70e43a0bb8a13953b04a90f76428b4959bb6 # v2.2.0
        with:
          key: doc
      - run: cargo doc --document-private-items

  run_tests:
    name: Run Cargo Tests
    needs:
      - run_cargodeny
      - run_clippy
      - run_rustfmt
      - run_rustdoc
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3.3.0
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: ${{ env.RUST_TOOLCHAIN_VERSION }}
      - uses: Swatinem/rust-cache@359a70e43a0bb8a13953b04a90f76428b4959bb6 # v2.2.0
        with:
          key: test
      - eun: cargo test

  tests_passed:
    name: All tests passed
    needs:
      - run_udeps
      - run_tests
    runs-on: ubuntu-latest
    steps:
      - name: log
        run: echo All tests have passed!
```

</details>

### `actions/setup-python` related changes

The action needs to be updated to at least version `4.3.0`. This version bumps `@actions/core` to `1.10.0`. See release
notes [here][2].

[1]: https://github.com/dtolnay/rust-toolchain
[2]: https://github.com/actions/setup-python/releases/tag/v4.3.0
