### ISSUE TITLE
Extend Tilt set-up to run openshift templating

### ISSUE THREAD

**Issue by adwk67** [stackabletech/issues#391]
Running/deploying operators against openshift clusters with Tilt does not apply this templating to the operator clusterrole, resulting in test failures:

```
{{ if .Capabilities.APIVersions.Has "security.openshift.io/v1" }}
  - apiGroups:
      - security.openshift.io
    resources:
      - securitycontextconstraints
    resourceNames:
      - airflow-scc
    verbs:
      - use
{{ end }}
```
