### ISSUE TITLE
Integrate verification of image signatures into our monitoring

### ISSUE THREAD

**Issue by dervoeti** [stackabletech/issues#409]
As Stackable, we want to make sure all our images (products, operators, mirrored images) are signed by us. We should integrate verification of these signatures into our nightly tests. A failing verification might indicate a security breach. Also, invalid or missing signatures on a future release will result in Pods failing to start in clusters, where customers have enforced signature verification themselves.
All 0.0.0-dev images and all future releases (starting with 23.11) should have valid signatures.
We could install Kyverno at the beginning of our tests (or at least one of them) and add a ClusterPolicy that enforces correct image signatures and also makes sure the signing process itself was publicly recorded in Rekor:
```yaml
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: verify-image-signatures
  namespace: default
spec:
  validationFailureAction: Enforce
  background: false
  failurePolicy: Fail
  rules:
    - name: verify-stackable-signatures
      match:
        any:
          - resources:
              kinds:
                - Pod
      verifyImages:
        - imageReferences:
            - "*.stackable.tech/*"
          attestors:
            - entries:
                - keyless:
                    issuer: "https://token.actions.githubusercontent.com"
                    subject: "https://github.com/stackabletech/*"
                    rekor:
                      url: https://rekor.sigstore.dev
```

In the future, we could even use Kyverno Policies to enforce other constraints in our tests, like:
 - Resource limits present on all containers
 - No privileged pods present
 - Block images larger than 3GB
 - Block stale images (older than 6 months)
 - Ensure all images have an SBOM attested
 - Ensure images don't contain known critical vulnerabilities
 - For more inspiration, see https://kyverno.io/policies/
 
 That's out of scope for this issue, though.
