### ISSUE TITLE
Research 3.3.6 issues

### ISSUE THREAD

**Issue by soenkeliebau** [stackabletech/issues#448]
I can't get Hadoop 3.3.6 to run on my local laptop. Older versions 3.2.4 and 3.3.4 work, but not the latest. Jenkins with Azure seems fine (modulo flakiness) so maybe it's just my machine. I stumbled on it by accident while trying to do something completely unrelated and I spent half a day on it now. I'm writing here just for the protocol.

I can reproduce with `beku -s smoke-latest` and `kuttl test` even if I create fresh kind clusters.

The `namenode-1` refuses to come up because the `format-namenode` container fails. I attach the log here.

Zookeeper seems to be happy.

The journal node only logs:

```
 java.nio.channels.ClosedChannelException                                                                                                                                                   │
│     at java.base/sun.nio.ch.SocketChannelImpl.ensureOpenAndConnected(SocketChannelImpl.java:180)                                                                                           │
│     at java.base/sun.nio.ch.SocketChannelImpl.write(SocketChannelImpl.java:452)                                                                                                            │
│     at org.apache.hadoop.ipc.Server.channelWrite(Server.java:3743)                                                                                                                         │
│     at org.apache.hadoop.ipc.Server.access$1800(Server.java:148)                                                                                                                           │
│     at org.apache.hadoop.ipc.Server$Responder.processResponse(Server.java:1722)                                                                                                            │
│     at org.apache.hadoop.ipc.Server$Responder.doRespond(Server.java:1792)                                                                                                                  │
│     at org.apache.hadoop.ipc.Server$Connection.sendResponse(Server.java:2919)                                                                                                              │
│     at org.apache.hadoop.ipc.Server$Connection.access$400(Server.java:1864)                                                                                                                │
│     at org.apache.hadoop.ipc.Server$RpcCall.doResponse(Server.java:1176)                                                                                                                   │
│     at org.apache.hadoop.ipc.Server$Call.doResponse(Server.java:954)                                                                                                                       │
│     at org.apache.hadoop.ipc.Server$Call.sendResponse(Server.java:940)                                                                                                                     │
│     at org.apache.hadoop.ipc.Server$RpcCall.run(Server.java:1111)                                                                                                                          │
│     at org.apache.hadoop.ipc.Server$RpcCall.run(Server.java:1017)                                                                                                                          │
│     at java.base/java.security.AccessController.doPrivileged(Native Method)                                                                                                                │
│     at java.base/javax.security.auth.Subject.doAs(Subject.java:423)                                                                                                                        │
│     at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1899)                                                                                                │
│     at org.apache.hadoop.ipc.Server$Handler.run(Server.java:3048)
```

My env
```
❯ k version
Client Version: v1.28.3
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.27.3
❯ kind --version
kind version 0.20.0
```
[namenode-1.log](https://github.com/stackabletech/issues/files/13162769/namenode-1.log)

**Comment by razvan** [comment]
**Update**: setting the log level to DEBUG on the namenode _fixes_ the problem.
Here is a working version:
```
---
apiVersion: kuttl.dev/v1beta1
kind: TestStep
metadata:
  name: install-hdfs
timeout: 180
---
apiVersion: hdfs.stackable.tech/v1alpha1
kind: HdfsCluster
metadata:
  name: hdfs
spec:
  image:
    productVersion: "3.3.6"
  clusterConfig:
    zookeeperConfigMapName: hdfs-zk
    dfsReplication: 1
    listenerClass: external-unstable
  nameNodes:
    config:
      logging:
        enableVectorAgent: False
    roleGroups:
      default:
        replicas: 2
        config:
          logging:
            containers:
              hdfs:
                console:
                  level: DEBUG
                file:
                  level: DEBUG
                loggers:
                  ROOT:
                    level: DEBUG
              vector:
                console:
                  level: DEBUG
                file:
                  level: DEBUG
                loggers:
                  ROOT:
                    level: DEBUG
  dataNodes:
    config:
      logging:
        enableVectorAgent: False
      resources:
        storage:
          data: # We need to overwrite the data pvcs coming from the default value
            count: 0
          hdd:
            capacity: 2Gi
            count: 2
            hdfsStorageType: Disk
          ssd:
            capacity: 1Gi
            # storageClass: premium # We can't set the storage class in itegration tests, as we don't know which ones are available
            count: 1
            hdfsStorageType: SSD
    roleGroups:
      default:
        replicas: 2
        config:
          logging:
            containers:
              hdfs:
                console:
                  level: DEBUG
                file:
                  level: DEBUG
                loggers:
                  ROOT:
                    level: DEBUG
              vector:
                console:
                  level: DEBUG
                file:
                  level: DEBUG
                loggers:
                  ROOT:
                    level: DEBUG
  journalNodes:
    config:
      logging:
        enableVectorAgent: False
    roleGroups:
      default:
        replicas: 1
        podOverrides:
          spec:
            containers:
              - name: journalnode
                resources:
                  requests:
                    cpu: 110m
                  limits:
                    cpu: 410m
        config:
          logging:
            containers:
              hdfs:
                console:
                  level: DEBUG
                file:
                  level: DEBUG
                loggers:
                  ROOT:
                    level: DEBUG
              vector:
                console:
                  level: DEBUG
                file:
                  level: DEBUG
                loggers:
                  ROOT:
                    level: DEBUG
```
