### ISSUE TITLE
Rego enrichment idea

### ISSUE THREAD

**Issue by fhennig** [stackabletech/issues#532]
Let's say I have a trino cluster

```yaml
---
apiVersion: trino.stackable.tech/v1alpha1
kind: TrinoCluster
metadata:
  name: simple-trino
  labels:
    dev: true
spec:
  image:
    productVersion: "428"
  clusterConfig:
    authorization:
      opa:
        configMapName: my-opa
        package: myRules
    listenerClass: external-unstable
  coordinators:
    roleGroups:
      default:
        replicas: 1
  workers:
    roleGroups:
      default:
        replicas: 1
```

based on the cluster meta information (name, labels) and the package that the user wants to call, we could add an intermediate rego rule that we generate:

```rego
package enrichRequest.simpleTrino # auto generated package name

import rego.v1
import myRules  # package name taken from the clusterConfig

allow if {
    myRules.allow with input as {   # package name taken from the clusterConfig
        "product": "trino",
        "cluster": {  # the name and labels are taken from the kubernetes metadata
            "name": "simple-trino",
            "labels": {
                "dev": true
            }
        },
        "request": input
    }
}
```

The user would then receive the enriched request in their `myRules` package without even knowing about how it worked. The file above could be completely auto-generated.
