### ISSUE TITLE
decision: Make autoTls certificate lifetime configurable

### ISSUE THREAD

**Issue by razvan** [stackabletech/issues#673]
Decision for https://github.com/stackabletech/issues/issues/586

# Problem

Some data products are very fragile when some of their services are restarted. These restarts may induce long response times or even data loss causing major disruptions in production environments.

When the secret operator generates self signed certificates, consumers cannot easily request a validity lifetime. Pod overrides can be used as a workaround but as usual with this mechanism, the user experience is bad and the platform exposes much more internals than necessary.

If not specifically requested, the secret operator uses a default value of 24 hours for the lifetime of the mounted TLS certificates.

Before the certificate lifetime expires, the requesting Pods are restarted to receive fresh certificates. In production environments, this value has been proven to be very disruptive and customers have requested to increase it.

# Proposal

We propose to make the certificate lifetime configurable via a new field called `requestedSecretLifetime` at group level.

An example snippet from the HDFS operator:

```
---
apiVersion: hdfs.stackable.tech/v1alpha1
kind: HdfsCluster
metadata:
  name: hdfs
spec:
  nameNodes:
    config:
      requestedSecretLifetime: 14d
  journalNodes:
    config:
      requestedSecretLifetime: 7d
  dataNodes:
    roleGroups:
      ssd-machines:
        config:
          requestedSecretLifetime: 1d
      hdd-machines:
        config:
          requestedSecretLifetime: 3d
```

Each operator will define a sensible set of default values at role level as appropriate.

This would support longer restart intervals for  critical services that may experience data loss and shorter restart intervals for other high-available services like HDFS data nodes.

# Alternatives

The following alternatives have been considered and dismissed.

### Cluster wide

Alternatively, a configuration property could be added to the individual cluster configuration types for each operator like this:

```
---
apiVersion: hdfs.stackable.tech/v1alpha1
kind: HdfsCluster
metadata:
  name: hdfs
spec:
 clusterConfig:
    requestedSecretLifetime: "7d"
```

This is considered a bit too restrictive.

### Role config

This approach is rejected largely because it's unnecessarily restrictive. The current convention is to make every configuration property available at group level by default unless it's not possible to do so.

We do not have real world examples where this level of flexibility is a requirement but we choose to not exclude  them as a possibility either.

```
---
apiVersion: hdfs.stackable.tech/v1alpha1
kind: HdfsCluster
metadata:
  name: hdfs
spec:
 nameNodes:
    requestedSecretLifetime: "7d"
 journalNodes:
    requestedSecretLifetime: "7d"
 dataNodes:
    requestedSecretLifetime: "7d" 
```

# Further consideration

We can see a future where not just the lifetime of self signed certificates can be managed by this property but also other types of secrets like keytabs.

Therefore the naming of the property was chosen to be general enough but also a counterpart to the  `maxCertificateLifetime` property of the `SecretClass`. 

# POC (outdated)

_This POC was made for the role level configuration._

A POC implementation for the HDFS operator is linked below.

* https://github.com/stackabletech/operator-rs/pull/908
* https://github.com/stackabletech/hdfs-operator/pull/615

# Reference

* https://github.com/stackabletech/issues/issues/586
