### ISSUE TITLE
smarter way to read external db credentials, db url, etc.

### ISSUE THREAD

**Issue by maxgruber19** [stackabletech/issues#681]
## description
some systems require a backend db to store internal things like hive, superset or airflow. for superset and airflow it's "spec.clusterConfig.credentialsSecret". those components require a special format / keys in the secret, so the secret has to be created manually / by job all the time. password changes are hard to track.

## solution
i think it would be less complicated if the secret can have arbitrary structure but the user can name the secret keys which should be used to retrieve password, jdbc url, whatever. idea is inspired by https://artifacthub.io/packages/helm/bitnami/keycloak?modal=values&path=auth for example 

```
auth:
  ...
  existingSecret: ""
  passwordSecretKey: ""
  ...
```

popular operators like https://cloudnative-pg.io/ create a secret with every spawned cluster containing all secret information required for stackable components. see the contents of the auto created secret here https://cloudnative-pg.io/documentation/1.19/applications/#secrets

### superset.yaml
```
---
apiVersion: superset.stackable.tech/v1alpha1
kind: SupersetCluster
metadata:
  name: simple-superset
spec:
  image:
    productVersion: 4.0.2
  clusterConfig:
    credentials:
      secretName: superset-secret
      secretKeys:
         connectionsSqlAlchemyDatabaseUri: uri
         adminUserPassword: password
         ...
    listenerClass: external-unstable
  nodes:
    roleGroups:
      default:
        config:
          rowLimit: 10000
          webserverTimeout: 300
```
