### ISSUE TITLE
Fix getting_stated template version variables

### ISSUE THREAD

**Issue by NickLarsenNZ** [stackabletech/issues#703]
## Problem

Currently we have one set of version variables for templating the `getting_started` script, which is used for both:
- Operator version tags.
- Product version tags.

This is usually fine for a release, however it makes release-candidates difficult.

For example, the tags for zookeeper will be:
- Operator: `25.3.0-pr925` (each operator will have a different PR number)
- Product: `3.9.3-stackable25.3.0-rc1`

## Proposal

Rename, and introduce a new set of variables:

```yaml
versions:
  # was `commons`
  commons-operator: 0.0.0-dev
  # was `zookeeper`
  zookeeper-operator: 0.0.0-dev # can be overridden with 25.3.0-pr925 during RC testing
  zookeeper-product: 3.9.3-stackable0.0.0-dev # can be overridden with 3.9.3-stackable25.3.0-rc1 during RC testing
```

_Purposefully not using the old variable names to reduce error_

Fix the usages of the usages, eg:

```diff
 stackablectl operator install \
-   commons={{ versions.commons }} \
+   commons={{ versions.commons-operator }} \
-   zookeeper={{ versions.zookeeper }}
+   zookeeper={{ versions.zookeeper-operator }}
```

```diff
 kubectl run my-pod \
   --stdin --tty --quiet --restart=Never \
-  --image oci.stackable.tech/sdp/zookeeper:3.9.3-stackable{{ versions.zookeeper }} -- \
+  --image oci.stackable.tech/sdp/zookeeper:{{ versions.zookeeper-product }} -- \
```

## Tasks

- Fix on `main` branch
- Cherry pick onto `pr-25.3.0` branch

```[tasklist]
### Operators
- [ ] airflow-operator `main` branch PR 
- [ ] airflow-operator `pr-25.3.0` branch PR 
- [ ] commons-operator `main` branch PR 
- [ ] commons-operator `pr-25.3.0` branch PR 
- [ ] druid-operator `main` branch PR 
- [ ] druid-operator `pr-25.3.0` branch PR 
- [ ] hbase-operator `main` branch PR 
- [ ] hbase-operator `pr-25.3.0` branch PR 
- [ ] hdfs-operator `main` branch PR 
- [ ] hdfs-operator `pr-25.3.0` branch PR 
- [ ] hive-operator `main` branch PR 
- [ ] hive-operator `pr-25.3.0` branch PR 
- [ ] kafka-operator `main` branch PR 
- [ ] kafka-operator `pr-25.3.0` branch PR 
- [ ] listener-operator `main` branch PR 
- [ ] listener-operator `pr-25.3.0` branch PR 
- [ ] nifi-operator `main` branch PR 
- [ ] nifi-operator `pr-25.3.0` branch PR 
- [ ] opa-operator `main` branch PR 
- [ ] opa-operator `pr-25.3.0` branch PR 
- [ ] secret-operator `main` branch PR 
- [ ] secret-operator `pr-25.3.0` branch PR 
- [ ] spark-k8s-operator `main` branch PR 
- [ ] spark-k8s-operator `pr-25.3.0` branch PR 
- [ ] superset-operator `main` branch PR 
- [ ] superset-operator `pr-25.3.0` branch PR 
- [ ] trino-operator `main` branch PR 
- [ ] trino-operator `pr-25.3.0` branch PR 
- [ ] zookeeper-operator `main` branch PR 
- [ ] zookeeper-operator `pr-25.3.0` branch PR 
```
