### ISSUE TITLE
Install products from the same registry as the ops themselves

### ISSUE THREAD

**Issue by razvan** [stackabletech/issues#716]
## Use case

In the following use-cases:

* SDP installations from private registries.
* OpenShift installations.
* Harbour connectivity problems (due to firewall rules)

product images are still loaded from `oci.stackable.tech` by default.

User's can configure custom images for products, but this has it's own set of problems:

* Users need to know the names of all images used by an operator.
* Some operators do not respect these properties (ex. secret, listener).

## Proposed solution

By default, operators should resolve to product images the same registry as their own origin.

**Comment by Techassi** [comment]
A few thoughts on this:

- The operator must never assume where it was installed from which is further used to derive which image index URI should be used. Instead, the operator needs to be launched with explicit values set.
- The product image selection mechanism must not default to `oci.stackable.tech` as the default registry. Instead, the explicit value provided on startup of the operator must be used. The selection mechanism API must be adjusted accordingly.
- When the operator is deployed via Helm (and OLM), Helm must provide data about the installation source. The value can be passed as environment variables in templated Deployments and DaemonSets.
- The Helm Chart must store data to provide the installation source during `helm install`. The chart provides a well-defined mechanism for this: custom annotations.
- The local Tilt workflow must continue to work.
- Our CI pipelines must publish container images and Helm Charts to both `oci.stackable.tech` **AND** `quay.io`. This removes the mirroring jobs and results in one canonical source for container images and Helm Charts.

The flow of installation source data will then look like this:

1. The destination where images and Helm Charts are published is known during operator container image build time in our automated CI pipeline. The publish targets can be defined as matrix dimensions. This will roughly look like this:

   ```yaml
   jobs:
     build-container-image:
       strategy:
         fail-fast: false
         matrix:
           # This matrix dimension is already present currently
           runner:
           - { name: "ubuntu-latest", arch: "amd64" }
           - { name: "ubicloud-standard-8-arm", arch: "arm64" }
           # This dimension will be NEW
           # The repository key can also be named namespace, because it will
           # most likely not describe the full repository, which also includes
           # the final part fo the path.
           # We will also have to deal with different credentials
           # (username and password/token) for the individual publish targets.
           publish-target:
           - { registry-uri: "oci.stackable.tech", repository: "sdp" }
           - { registry-uri: "quay.io", repository: "stackable" }
        steps:
        # ...
        - name: Publish Container Image
          if: ${{ !github.event.pull_request.head.repo.fork }}
          uses: stackabletech/actions/publish-image
          with:
            image-registry-uri: ${{ matrix.publish-target.registry-uri }}
            image-repository: ${{ matrix.publish-target.repository }}/${{ env.OPERATOR_NAME }}
            # ...
              
     publish-index-manifest:
       needs:
       - build-container-image
      # This whole strategy block will be NEW
      strategy:
         fail-fast: false
         matrix:
           publish-target:
           - { registry-uri: "oci.stackable.tech", repository: "sdp" }
           - { registry-uri: "quay.io", repository: "stackable" }
      steps:
      # ...
      - name: Publish and Sign Image Index
        uses: stackabletech/actions/publish-image-index-manifest
        with:
          image-registry-uri: ${{ matrix.publish-target.registry-uri }}
          image-repository: ${{ matrix.publish-target.repository }}/${{ env.OPERATOR_NAME }}
          # ...
          
      publish-helm-chart:
        needs:
        - build-container-image
        # This whole strategy block will be NEW
        strategy:
           fail-fast: false
           matrix:
             publish-target:
             - {
                 registry-uri: "oci.stackable.tech",
                 chart-repository: "sdp-charts",
                 image-repository: "sdp"
               }
             - {
                 registry-uri: "quay.io",
                 # This needs to be decided
                 chart-repository: "stackable-charts",
                 image-repository: "stackable"
               }
        steps:
        - name: Package, Publish, and Sign Helm Chart
          # This action needs to dynamically add the annotations with the
          # installation source data going forward.
          uses: stackabletech/actions/publish-helm-chart
          with:
            chart-registry-uri: ${{ matrix.publish-target.registry-uri }}
            chart-repository: ${{ matrix.publish-target.chart-repository }}
            # ...
   ```
2. The Helm Chart will include installation source data. These pieces of data are stored using the dedicated mechanism to include custom data in Helm Charts: annotations.
   
   ```yaml
   apiVersion: v2
   name: airflow-operator
   version: 0.0.0-dev
   appVersion: 0.0.0-dev
   # ...
   # This whole block will be NEW
   annotations:
     imageRegitstryUri: oci.stackable.tech # or quay.io
     imageRepositry: sdp/airflow-operator  # or stackable/airflow-operators
     # Potentially include this:
     imageNamespace: sdp                   # or stackable
   ```
   
  > [!NOTE]
  > There currently is no way to tell `helm package` to dynamically include annotations. We would likely need to resort to manual YAML wrangling. The same applies for the Tiltfile.

3. During Helm Chart installation via `helm install`, the image name for Deployments and DaemonSets is constructed during templating. Additionally, both the registry URI and repository are provided to the operator via environment variables. The image names can be overridden as already possible via `values.yaml`. Going forward, the default values for image names will **not** come from `.Values`, but instead from `.Chart.Annotations`.

   ```yaml
   apiVersion: apps/v1
   kind: Deployment
   spec:
     template:
       spec:
         containers:
         - name: {{ include "operator.appname" . }}
           image: {{ include "images.operator" . }} # A new template helper
           args:
           - run
           - controller
           env:
           - name: IMAGE_REGISTRY_URI
             value: {{ .Chart.Annotations.imageRegistryUri }}
           - name: IMAGE_REPOSITRY
             value: {{ .Chart.Annotations.imageRepository }}
           # ...
   ```
   
   The new `images.operator` template helper will basically work like this: If a custom `image` is specified using `values.yaml`, use that as the image source. Then fall back to constructing the image source from `.Chart.Annotations`. No other fallback/default exists.
4. The operator exposes new CLI arguments (which can also be set via environment variables). A good place for these would be `OperatorEnvironmentOptions`:

   ```rust
   #[derive(clap::Args)]
   #[command(next_help_heading = "Environment Options")]
   pub struct OperatorEnvironmentOptions {
        // ...

        #[arg(long, env)]
        pub image_registry_uri: url::Url,
     
        #[ærg(long, env)]
        pub image_repositry: String
   }
   ```
5. The two values from above can then be passed to `ProductImage::resolve` - either as two separate parameters, or as a single pre-parsed URL/URI.
