### ISSUE TITLE
chore(tracking): Update Rust dependencies of operators before SDP Release 25.7.0

### ISSUE THREAD

**Issue by NickLarsenNZ** [stackabletech/issues#725]
## Pre-Release Operator Rust Updates

Part of <https://github.com/stackabletech/issues/issues/722>

> [!TIP]
> Create branches with predictable names so the links below work. Remember
> to replace `25.7.0` with the appropriate release version:
>
> ```sh
> git stash -m "unsaved work"
> git fetch origin
> git checkout -b chore/bump-rust-deps-pre-25.7.0 origin/main
> ```
>
> Then use the links below to automatically create applicable PRs for each operator
> using the PR template.

### Bump op-rs to latest version

This will (most likely) require code changes and updates to the operator cluster rules.

Due to the addition of [automatic cluster domain detection](https://github.com/stackabletech/issues/issues/662), all operator cluster roles now require GET access to the kubelet API:

```yaml
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: operator-cluster-role
rules:
...
  # For automatic cluster domain detection
  - apiGroups:
      - ""
    resources:
      - nodes/proxy
    verbs:
      - get
...
```
### Operator Rust Updates

Replace the items in the task list below with the applicable Pull Requests.

- [x] https://github.com/stackabletech/airflow-operator/pull/656
- [x] https://github.com/stackabletech/commons-operator/pull/365
- [x] https://github.com/stackabletech/druid-operator/pull/735
- [x] https://github.com/stackabletech/hbase-operator/pull/675
- [x] https://github.com/stackabletech/hdfs-operator/pull/699
- [x] https://github.com/stackabletech/hive-operator/pull/615
- [x] https://github.com/stackabletech/kafka-operator/pull/878
- [x] https://github.com/stackabletech/listener-operator/pull/320
- [x] https://github.com/stackabletech/nifi-operator/pull/817
- [x] https://github.com/stackabletech/opa-operator/pull/743
- [x] https://github.com/stackabletech/secret-operator/pull/619
- [x] https://github.com/stackabletech/spark-k8s-operator/pull/592
- [x] https://github.com/stackabletech/superset-operator/pull/646
- [x] https://github.com/stackabletech/trino-operator/pull/771
- [x] https://github.com/stackabletech/zookeeper-operator/pull/961
