### ISSUE TITLE
Restrict and revisit Operator ClusterRoles and/or namespaced Roles

### ISSUE THREAD

**Issue by maltesander** [stackabletech/issues#727]
Currently, operators request access to secrets in all namespaces. Below is a snippet for ZooKeeper, that does not interact with Secrets.

```
  - apiGroups:
      - ""
    resources:
      - pods
      - configmaps
      - secrets
      - services
      - endpoints
      - serviceaccounts
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
```

While we have a couple of operators that do need to create and read (their secrets) for e.g. database decryption etc. like:

- NiFi
- Trino
- Superset

there are other operators that do not need to do that, like ZooKeeper.

We should revisit and restrict the ClusterRoles of operators to what they actually require (especially in terms of secrets).

Furthermore we should think about restricting the operators to only work (watch?) on a specified list of namespaces for better security and tenant separation.
